### ISSUE TITLE
Progress information

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [nngogol/PySimpleGUIDocGen#27]
I'm getting crashes due to stuff wrong in my .py file.   I'm pretty sure it's in the newly added Popup function tags.

Here's the error I get:

```
C:\Python\Anaconda3\python.exe C:/Python/PycharmProjects/GitHub/PySimpleGUIDocGen/db/usage.py
starting main
Traceback (most recent call last):
  File "C:/Python/PycharmProjects/GitHub/PySimpleGUIDocGen/db/usage.py", line 58, in <module>
    delete_html_comments=True)
  File "C:\Python\PycharmProjects\GitHub\PySimpleGUIDocGen\db\make_real_readme.py", line 457, in main
    content = render(injection)
  File "C:\Python\PycharmProjects\GitHub\PySimpleGUIDocGen\db\make_real_readme.py", line 268, in render
    doc_string=injection['function_object'].__doc__)
  File "C:\Python\PycharmProjects\GitHub\PySimpleGUIDocGen\db\make_real_readme.py", line 244, in get_sig_table_parts
    get_params_part(doc_string).items()])
  File "C:\Python\PycharmProjects\GitHub\PySimpleGUIDocGen\db\make_real_readme.py", line 84, in get_params_part
    only_params = code[code.index(':param'):]  # get_only_params_string(code)
ValueError: substring not found

Process finished with exit code 1
```

The problem is that I have no feedback that tells me perhaps WHICH tag had trouble, or which tags had been processed before it with no problems.

Is there a way we can add to the log file the tags as they are being processed correctly?  Then I could look in there and see how far it made it.

**Comment by nngogol** [comment]
You had used old stuff.
Last changed is logging a lot of stuff - check it out.
