### ISSUE TITLE
Way of marking a class, method, func as not one to create a tag in show_all_tags 

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [nngogol/PySimpleGUIDocGen#47]
I run show all tags, then I need to pick through and take out things that are 'private' that don't start with an _.

Can I put something in the header that will cause you to skip it?

I just completed removing all of the tags from the main doc  and moved them to the bottom.  Running my first complete pass next...

**Comment by nngogol** [comment]
done

**Comment by PySimpleGUI** [comment]
I pulled over the new make_real_readme and I now get this error:

```
C:\Python\Anaconda3\python.exe C:/Python/PycharmProjects/GooeyGUI/readme_creator/run_me.py
Traceback (most recent call last):
  File "C:/Python/PycharmProjects/GooeyGUI/readme_creator/run_me.py", line 81, in <module>
    delete_html_comments=True)
  File "C:\Python\PycharmProjects\GooeyGUI\readme_creator\make_real_readme.py", line 596, in main
    content = render(injection, logger=logger, line_break=line_break, insert_md_section_for__class_methods=insert_md_section_for__class_methods,)
  File "C:\Python\PycharmProjects\GooeyGUI\readme_creator\make_real_readme.py", line 378, in render
    doc_string=injection['function_object'].__doc__, logger=logger, line_break=line_break)
  File "C:\Python\PycharmProjects\GooeyGUI\readme_creator\make_real_readme.py", line 309, in get_sig_table_parts
    sign = "\n\n{0}\n\n```\n{1}({2})\n```".format(get_doc_desc(doc_string, function_obj), function_name, sig_content)
  File "C:\Python\PycharmProjects\GooeyGUI\readme_creator\make_real_readme.py", line 264, in get_doc_desc
    if return_in: doc_string = doc_string[:doc_string.index(':return:')]
ValueError: substring not found

Process finished with exit code 1
```

Did I need to get anything else?
Note that I launch everything using this run_me.py file.


[run_me.py.txt](https://github.com/nngogol/PySimpleGUIDocGen/files/3535182/run_me.py.txt)
