### ISSUE TITLE
Weird crash when including this function definition

### ISSUE THREAD

**Issue by PySimpleGUI** [nngogol/PySimpleGUIDocGen#51]
I was trying to get 4.5.0 out a couple days back and could not for the life of me get past the problem when I had this in the 2_readme.md:

`<!-- <+func.popup_ok_cancel+> -->`

When I place that line after the popup_ok definition, I get this crash that I tried and tried to understand but just couldn't figure it out, so I deleted the function from the docs.  Maybe you can help me get past it....

```
C:\Python\Anaconda3\python.exe C:/Python/PycharmProjects/GooeyGUI/readme_creator/run_me.py
Traceback (most recent call last):
  File "C:/Python/PycharmProjects/GooeyGUI/readme_creator/run_me.py", line 81, in <module>
    delete_html_comments=True)
  File "C:\Python\PycharmProjects\GooeyGUI\readme_creator\make_real_readme.py", line 610, in main
    insert_md_section_for__class_methods=insert_md_section_for__class_methods,)
  File "C:\Python\PycharmProjects\GooeyGUI\readme_creator\make_real_readme.py", line 380, in render
    doc_string=injection['function_object'].__doc__, logger=logger, line_break=line_break)
  File "C:\Python\PycharmProjects\GooeyGUI\readme_creator\make_real_readme.py", line 302, in get_sig_table_parts
    raise Exception(f'IDK this type -> {key, val}')
Exception: IDK this type -> ('icon', b'R0lGODlhIQAgAPcAAAAAADBpmDBqmTFqmjJrmzJsnDNtnTRrmTZtmzZumzRtnTdunDRunTRunjVvnzdwnzhwnjlxnzVwoDZxoTdyojhzozl0ozh0pDp1pjp2pjp2pzx0oj12pD52pTt3qD54pjt4qDx4qDx5qTx5qj16qj57qz57rD58rT98rkB4pkJ7q0J9rEB9rkF+rkB+r0d9qkZ/rEl7o0h8p0x9pk5/p0l+qUB+sEyBrE2Crk2Er0KAsUKAskSCtEeEtUWEtkaGuEiHuEiHukiIu0qKu0mJvEmKvEqLvk2Nv1GErVGFr1SFrVGHslaHsFCItFSIs1COvlaPvFiJsVyRuWCNsWSPsWeQs2SQtGaRtW+Wt2qVuGmZv3GYuHSdv3ievXyfvV2XxGWZwmScx2mfyXafwHikyP7TPP/UO//UPP/UPf/UPv7UP//VQP/WQP/WQf/WQv/XQ//WRP7XSf/XSv/YRf/YRv/YR//YSP/YSf/YSv/ZS//aSv/aS/7YTv/aTP/aTf/bTv/bT//cT/7aUf/cUP/cUf/cUv/cU//dVP/dVf7dVv/eVv/eV//eWP/eWf/fWv/fW/7cX/7cYf7cZP7eZf7dav7eb//gW//gXP/gXf/gXv/gX//gYP/hYf/hYv/iYf/iYv7iZP7iZf/iZv/kZv7iaP/kaP/ka//ma//lbP/lbv/mbP/mbv7hdP7lcP/ncP/nc//ndv7gef7gev7iff7ke/7kfv7lf//ocf/ocv/odP/odv/peP/pe//ofIClw4Ory4GszoSszIqqxI+vyoSv0JGvx5OxyZSxyZSzzJi0y5m2zpC10pi715++16C6z6a/05/A2qHC3aXB2K3I3bLH2brP4P7jgv7jh/7mgf7lhP7mhf7liv/qgP7qh/7qiP7rjf7sjP7nkv7nlv7nmP7pkP7qkP7rkv7rlv7slP7sl/7qmv7rnv7snv7sn/7un/7sqv7vq/7vrf7wpv7wqf7wrv7wsv7wtv7ytv7zvP7zv8LU48LV5c3a5f70wP7z0AAAACH5BAEAAP8ALAAAAAAhACAAAAj/AP8JHEiwoMGDCA1uoYIF4bhK1vwlPOjlQICLApwVpFTGzBk1siYSrCLgoskFyQZKMsOypRyR/GKYnBkgQbF/s8603KnmWkIaNIMaw6lzZ8tYB2cIWMo0KIJj/7YV9XgGDRo14gpOIUBggNevXpkKGCDsXySradSoZcMmDsFnDxpEKEC3bl2uXCFQ+7emjV83bt7AgTNroJINAq0wWBxBgYHHdgt0+cdnMJw5c+jQqYNnoARkAx04kPEvS4PTqBswuPIPUp06duzcuYMHT55wAjkwEahsQgqBNSQIHy582D9BePTs2dOnjx8/f1gJ9GXhRpTqApFQoDChu3cOAps///9D/g+gQvYGjrlw4cU/fUnYX6hAn34HgZMABQo0iJB/Qoe8UxAXOQiEg3wIXvCBQLUU4mAhh0R4SCLqJOSEBhhqkAEGHIYgUDaGICIiIoossogj6yBUTQ4htNgiCCB4oIJAtJTIyI2MOOLIIxMtQQIJIwQZpAgwCKRNI43o6Igll1ySSTsI7dOECSaUYOWVKwhkiyVMYuJlJpp0IpA6oJRTkBQopHnCmmu2IBA2mmQi5yZ0fgJKPP+0IwoooZwzkDQ2uCCoCywUyoIW/5DDyaKefOLoJ6LU8w87pJgDTzqmDNSMDpzqYMOnn/7yTyiglBqKKKOMUopA7JgCy0DdeMEjUDM71GqrrcH8QwqqqpbiayqToqJKLwN5g45A0/TAw7LL2krGP634aoopp5yiiiqrZLuKK+jg444uBIHhw7g+MMsDFP/k4wq22rririu4xItLLriAUxAQ5ObrwzL/0PPKu7fIK3C8uxz0w8EIIwzMP/cM7HC88hxEzBBCBGGxxT8AwQzDujws7zcJQVMEEUKUbPITAt1D78OSivSFEUXEXATKA+HTscC80CPSQNGEccQRYhjUDzfxcjPPzkgnLVBAADs=')

Process finished with exit code 1
```

**Comment by PySimpleGUI** [comment]
Oh, I run a program called "run_me.py" to make the docs.  It pops up a window at the end when it works.  It crashes like above when it doesn't.

The files are all checked into the PySimpleGUI GitHub under readme_creator:
https://github.com/PySimpleGUI/PySimpleGUI/tree/master/readme_creator

**Comment by nngogol** [comment]
I didn't understand anything. Can you describe it more clearly?
How can I reproduce error?
I need clear picture of a problem and environment, when error occurred.

**Comment by PySimpleGUI** [comment]
The instructions are here in the Issue.

When I include the line:
`<!-- <+func.popup_ok_cancel+> -->`

It crashes when I run my normal creation program run_me.py

**Comment by PySimpleGUI** [comment]
OK, I've made it super-easy for you.

Download the folder readme_creator (link posted above)

run the file "run_me.py" and you'll get the crash

If you remove the line at end of section 2 then it doesn't crash.

**Comment by nngogol** [comment]
fixed/
