### ISSUE TITLE
Crashes when clicking button to open call reference.md

### ISSUE THREAD

**Issue by PySimpleGUI** [nngogol/PySimpleGUIDocGen#58]
```
C:\Python\Anaconda3\python.exe C:/Python/PycharmProjects/GooeyGUI/readme_creator/run_me.py
PSG event> -open_call_ref-
Traceback (most recent call last):
  File "C:/Python/PycharmProjects/GooeyGUI/readme_creator/run_me.py", line 379, in <module>
    mini_GUI()
  File "C:/Python/PycharmProjects/GooeyGUI/readme_creator/run_me.py", line 365, in mini_GUI
    if event == '-open_call_ref-':    openfile(CALL_REFERENCE_OFILENAME)
  File "C:/Python/PycharmProjects/GooeyGUI/readme_creator/run_me.py", line 20, in openfile
    os.startfile(a_path)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'output/call reference.md'

Process finished with exit code 1
```

**Comment by nngogol** [comment]
fixed
